# Generated by Django 4.0.5 on 2023-01-03 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfWords',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groups_of_words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word1', models.CharField(max_length=50)),
                ('word2', models.CharField(max_length=50)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', related_query_name='words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('duration', models.CharField(choices=[('finite', 'Test will end after all words are examined'), ('infinite', 'Test will run looped until you decide to finish')], max_length=50)),
                ('scoring_type', models.CharField(choices=[('ranked', 'Every mistake or success is counted'), ('unranked', "Results do not affect words' scores")], max_length=50)),
                ('word2examine_number', models.CharField(choices=[('1', 'Word to translation'), ('2', 'Translation to word')], max_length=50, verbose_name='Testing type')),
                ('do_with_incorrect', models.CharField(choices=[('skip', 'Go next if a mistake is made'), ('repeat', 'Reask until answer is correct')], max_length=50, verbose_name='Incorrect answer')),
                ('which_goes_first', models.CharField(choices=[('random', 'Random words are asked'), ('lower_score', 'Words with lower score asked firstly')], max_length=50, verbose_name='Word order')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_words', models.JSONField(default=dict)),
                ('details', models.JSONField(default={'fnl_res_4test_words': []})),
                ('ended', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='results', related_query_name='results', to='words.groupofwords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupofwords',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', related_query_name='groups', to='words.word'),
        ),
    ]
