# Generated by Django 4.0.5 on 2022-12-28 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_alter_result_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofwords',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groups_of_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupofwords',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', related_query_name='groups', to='words.word'),
        ),
    ]
