# Generated by Django 4.0.5 on 2023-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_groupofwords_user_alter_groupofwords_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='word2',
            field=models.CharField(max_length=50),
        ),
    ]
